### PR TITLE
Version number & python-dotenv

### PR DESCRIPTION
**Pull request by marksweb**
This brings back `python-dotenv` for easily injecting environment variables into anything running `manage.py` tasks.

I've also added a version number to `djangogirls.__init__.py`. which is then imported by settings and fed into sentry as the release number which would get attached to any issues for tracking which release they started in.

This ties in with #639 by explicitly adding a version. I think it's probably easier than using tags. You'll just need to increment the version number after merging PRs, before releasing.

In terms of details for versioning, it's good to follow https://semver.org/

### CODE REVIEW

**Review by amakarudze — CHANGES_REQUESTED** [review]
Since you added versioning which we didn't have, could you please include documentation on versioning in the `README.md` file? For future maintainers.

Thank you for your work on this @marksweb.

**Comment by carltongibson** [comment]
Hmm. Can we not just identify releases in Sentry by the commit hash, or something else automatic? (Otherwise bumping the version number become just another bit of busy work.)

Ideally we're _releasing_ on every commit to the main branch.

**Comment by carltongibson** [comment]
We should probably try to keep separate changes in separate PRs, since the dotenv change is likely fine...

**Comment by amakarudze** [comment]
> Hmm. Can we not just identify releases in Sentry by the commit hash, or something else automatic? (Otherwise bumping the version number become just another bit of busy work.)
> 
> Ideally we're _releasing_ on every commit to the main branch.

Yeah, agreed. We haven't bumped the version number before.

**Comment by amakarudze** [comment]
> We should probably try to keep separate changes in separate PRs, since the dotenv change is likely fine...

Great idea. Works well especially for me to debug when things break after deployment.

**Comment by marksweb** [comment]
> Hmm. Can we not just identify releases in Sentry by the commit hash, or something else automatic? (Otherwise bumping the version number become just another bit of busy work.)
> 
> Ideally we're _releasing_ on every commit to the main branch. 

Maybe. Did you say that python anywhere has a copy of the repo & pulls the latest @amakarudze ?

If so we can do it from the commit hash. I'm just used to servers that use copies of the code rather than actually having access to git.

**Comment by marksweb** [comment]
> We should probably try to keep separate changes in separate PRs, since the dotenv change is likely fine...

Typically I do, but I got conscious of the amount of PRs I'm generating 😂

**Comment by amakarudze** [comment]
> > We should probably try to keep separate changes in separate PRs, since the dotenv change is likely fine...
> 
> Typically I do, but I got conscious of the amount of PRs I'm generating 😂

Hahahaha 😂🤗. 

I do get it that there has been a considerable number of PRs from you but given the project has been stagnant for a while, there is bound to be a lot of work. Smaller PRs would be easier and faster to review and merge. 

We really do appreciate all the work you have done so far, though it has meant lots of PRs from you 😂.

**Comment by amakarudze** [comment]
> > Hmm. Can we not just identify releases in Sentry by the commit hash, or something else automatic? (Otherwise bumping the version number become just another bit of busy work.)
> > Ideally we're _releasing_ on every commit to the main branch.
> 
> Maybe. Did you say that python anywhere has a copy of the repo & pulls the latest @amakarudze ?
> 
> If so we can do it from the commit hash. I'm just used to servers that use copies of the code rather than actually having access to git.

Yes, we fetch latest commits from the repo.

**Comment by marksweb** [comment]
@amakarudze Ok I've updated this to use the git commit hash.

**Review by amakarudze — APPROVED** [review]

**Comment by amakarudze** [comment]
@marksweb I am getting a server error and this traceback so am reverting this PR.

```
Error running WSGI application
2021-08-19 15:40:06,959: git.exc.InvalidGitRepositoryError
2021-08-19 15:40:06,959:   File "/var/www/djangogirls_org_wsgi.py", line 30, in <module>
2021-08-19 15:40:06,959:     application = get_wsgi_application()
2021-08-19 15:40:06,959: 
2021-08-19 15:40:06,959:   File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2021-08-19 15:40:06,960:     django.setup(set_prefix=False)
2021-08-19 15:40:06,960: 
2021-08-19 15:40:06,960:   File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
2021-08-19 15:40:06,960:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2021-08-19 15:40:06,960: 
2021-08-19 15:40:06,960:   File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
2021-08-19 15:40:06,960:     self._setup(name)
2021-08-19 15:40:06,960: 
2021-08-19 15:40:06,960:   File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/conf/__init__.py", line 43, in _setup
2021-08-19 15:40:06,961:     self._wrapped = Settings(settings_module)
2021-08-19 15:40:06,961: 
2021-08-19 15:40:06,961:   File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/django/conf/__init__.py", line 106, in __init__
2021-08-19 15:40:06,961:     mod = importlib.import_module(self.SETTINGS_MODULE)
2021-08-19 15:40:06,961: 
2021-08-19 15:40:06,961:   File "/home/djangogirls2/djangogirls.com/djangogirls/settings.py", line 11, in <module>
2021-08-19 15:40:06,961:     repo = git.Repo(search_parent_directories=True)
2021-08-19 15:40:06,961: 
2021-08-19 15:40:06,961:   File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/git/repo/base.py", line 220, in __init__
2021-08-19 15:40:06,961:     self.working_dir = self._working_tree_dir or self.common_dir  # type: Optional[PathLike]
2021-08-19 15:40:06,962: 
2021-08-19 15:40:06,962:   File "/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/git/repo/base.py", line 303, in common_dir
2021-08-19 15:40:06,962:     raise InvalidGitRepositoryError()
```

**Comment by marksweb** [comment]
@amakarudze Oh no 😞 

I think it'd be good to see the build script, to get a better idea of what this environment does/has etc. 

We could really do with making local/dev environments more consistent with python anywhere, or visa versa.

In this instance, there's clearly something different about how git is setup on pythonanywhere which means it doesn't work like it does locally.

**Comment by amakarudze** [comment]
I have just done a PR to revert the work but haven't merged it. Just commented out the lines breaking the site in settings.py for now and it seems your `python-dotenv` work is harmless :). 

Yes, it seems git is set up differently on PythonAnywhere. May be we can check the forums? Also, I am only getting stack traces on Sentry for one of the 3 instances and not the other 2. We have a long way to go fixing this setup. Maybe I should add their URLs in Sentry?

**Comment by amakarudze** [comment]
Great work with codecov though, Slack notifications are failing though @marksweb .

**Comment by marksweb** [comment]
@amakarudze The slack webhook seems to just need the `SLACK_WEBHOOK` defined in the repo secrets. Is it there? 

Looks like there are other options you can provide to it, but that's the only one that's required;
https://github.com/rtCamp/action-slack-notify

**Comment by amakarudze** [comment]
Yes @marksweb, the `SLACK_WEBHOOK` is there.

**Comment by marksweb** [comment]
@amakarudze Ok there may be a problem with the format or the way it's defined/included because the action can't find it;

https://github.com/DjangoGirls/djangogirls/runs/3374530019?check_suite_focus=true

**Comment by amakarudze** [comment]
> @amakarudze Ok there may be a problem with the format or the way it's defined/included because the action can't find it;
> 
> https://github.com/DjangoGirls/djangogirls/runs/3374530019?check_suite_focus=true

@marksweb I have sent in a request to our Slack Admins. It might take some time since they are no longer active on Slack. Sorry about that.

**Pull request merged**
