### PR TITLE
Migrate website to Django 3.2

### PR DESCRIPTION
**Pull request by amakarudze**
Django Girls is considering a form on the website to enable one-time donations using Stripe. This has brought about the need to update the website from Django 2.x to Django 3.x. This pull request migrates Django to Django 3.2 and also updates all the other packages.

### CODE REVIEW

**Comment by amakarudze** [comment]
Hello @carltongibson. I have managed to get most of the tests to pass after bumping Django to 3.2 and upgrading most of the packages except for 3 tests and they all fail because of `django-recaptcha`. They pass on my local machine but fail in Travis. Please see the build and any suggestions on how to make them pass in Travis are greatly appreciated.

**Comment by carltongibson** [comment]
Hey @amakarudze — Ok, give me a few days to spin it up and have a look. (Pretty sure we have reCaptcha going on djangoproject.com so it should be OK.)

**Review by carltongibson — COMMENTED** [review]
Hey @amakarudze — so I get three failures: 

```
================================================================= short test summary info =================================================================
FAILED tests/contact/test_views.py::test_form_sends_email_to_support - assert 200 == 302
FAILED tests/contact/test_views.py::test_form_sends_email_to_chapter - assert 200 == 302
FAILED tests/contact/test_views.py::test_email_is_saved_into_database - assert 200 == 302
```

These are (as you say) because of the recaptcha. 

I'm wondering, do you have some local settings or vars configuring the recaptha? 🤔

(

**Comment by carltongibson** [comment]
Hey @amakarudze — looks like this issue with the captcha tests is a known-issue https://github.com/praekelt/django-recaptcha/issues/218. 

There are a few options starting from https://github.com/praekelt/django-recaptcha/issues/218#issuecomment-670849963
(I remember seeing this for djangoproject.com — I'm just trying to recall how we worked around it there.)

**Comment by amakarudze** [comment]
@carltongibson Thanks.

I just noticed the new Django Suit we use for our admin backend is breaking the interface so I will need to pick some useful commits. I am not sure if we will be able to go ahead and migrate as Django Suit has always stopped up migrating to a newer version of Django as they are behind in their support for Django 3.0 + versions. I can spin up a 3rd local venv and test the commits one by one and see if it works. 

Also would need to create a new virtualenv on PythonAnywhere and this might break things big time. Let's see how I can do this incrementally.

**Comment by carltongibson** [comment]
Hey @amakarudze — I'm still getting up to speed, but generally if we can merge one thing at a time and narrow down what's to be done, that helps. 

If we can update to the latest Django 2.2, and update the Python version, then we can bump dependencies one at a time. 
Happy to work with you on this.

**Comment by amakarudze** [comment]
Sure, thanks @carltongibson. Let me start by upgrading to 2.2 and then bump the version of Python.

**Comment by amakarudze** [comment]
Just noticed there is note in the requirements.txt that Django Suit breaks with Django 2.2. Let me see if that is still the case @carltongibson.

**Comment by amakarudze** [comment]
Too many commits in one PR. Closing this so the work can be done incrementally.

**Pull request closed without merging**
