### PR TITLE
Implementing flake8 with pre-commit action

### LINKED ISSUE #635: Introduce flake8 checks for code quality
I'm a fan of good quality code so keen to introduce [flake8](https://flake8.pycqa.org/en/latest/) to the project & have it running along with the actions.

There's about 150 issues that it's identifying, so wouldn't be a small PR, but it is just formatting, not functionality.

Issues should be fewer if the code quality is higher.

Would this be a welcome feature?

### PR DESCRIPTION
**Pull request by marksweb**
This implements `flake8` without really making changes besides formatting, apart from where I was able to swap out `''.format()` for F strings.

Closes #635

### CODE REVIEW

**Review by amakarudze — APPROVED** [review]
Looks good to me. Thanks @marksweb for your work in this.

**Comment by amakarudze** [comment]
Does this need any rebasing or its good to go as is @marksweb?

**Comment by marksweb** [comment]
@amakarudze I've rebased just to be sure 👍

**Comment by marksweb** [comment]
@amakarudze I've rebased & verified changes meet flake8 👍

**Pull request merged**
