### PR TITLE
Add empty coach image for #291

### PR DESCRIPTION
**Pull request by sodevious**
Adds a default image when there has been no coach image selected: https://github.com/DjangoGirls/djangogirls/issues/291

### CODE REVIEW

**Comment by aniav** [comment]
Hey @sodevious the idea of using the heart as an empty coach photo is awesome! <3
I would like to suggest putting the photo link somewhere on the coach model, so when it is retrieved in other places it will still look the same. For example there is a coach list in the admin and we won't have the empty image there. Do you think you might make such change? ✨

**Comment by sodevious** [comment]
Good idea! Let me try that :)

**Comment by aniav** [comment]
@sodevious need any help with that? :)

**Comment by aniav** [comment]
@sodevious I have used your changes and implemented the coach photo as a property on the model. Thank you for your help here! 👍 ❤️

**Pull request closed without merging**
