### PR TITLE
Captcha

### PR DESCRIPTION
**Pull request by patjouk**
Two little things in this PR:
- Captcha added to contact form
- On newsletter page, previous dispatches were listed from the oldest to the newest: it's probably better to have the latest first ;)

### CODE REVIEW

**Comment by olasitarska** [comment]
On testing locally, I get this:

screenshot 2016-02-08 09 28 00

Is that expected?

**Comment by patjouk** [comment]
Because of how Recaptcha works, the widget will always show an error in local mode but now, it will be possible to save a form in local, even if it's still complaining :wink:

**Comment by olasitarska** [comment]
Excellent! :)

**Comment by olasitarska** [comment]
Thanks! :panda_face:

**Pull request merged**
