### PR TITLE
Typo with dependency to translation files in application/decorator

### PR DESCRIPTION
**Pull request by anaschwendler**
In order to fix the typo from the issue we need to run `django-admin makemessages --all` to regenerate the translations :)
This PR looks forward to that, I hope.

Solves #910 

Thanks!

### CODE REVIEW

**Review by marksweb — APPROVED** [review]

**Comment by marksweb** [comment]
@anaschwendler I just looked to get these changes updated in the translation branch and there were lots of conflicts.

That branch is used to integrate the project with the people doing the translations on https://poeditor.com

I've resolved the conflicts by accepting the changes on that branch so we don't lose any translations.

I think what you've done here will need to be done again once we get that branch merged into main & everything is up to day - sorry!

**Comment by anaschwendler** [comment]
>I think what you've done here will need to be done again once we get that branch merged into main & everything is up to day - sorry!

I can do it after, no problems, just let me know, also I'm also trying to understand how can I solve the invalid locale, if you have a guess 🤔

**Comment by marksweb** [comment]
@anaschwendler Ok I've updated the `main` branch with the latest translations from poeditor and fixed the tests.

I also added an explanation of the Brazilian confusion on #910 

So I think you can re-do this and raise a new PR.

**Comment by anaschwendler** [comment]
Hey @marksweb thank you very for checking into that :)
I'll re-open it soon!

**Pull request merged**
