### PR TITLE
[WIP] Switching from Campaign Monitor to Mailchimp

### PR DESCRIPTION
**Pull request by patjouk**
I'm starting to move our newsletter from Campaign Monitor to Mailchimp.
I've kept an old campaign in Mailchimp (t-shirt sale) for the test. I'll remove it when we will deploy.

- [x] Update Dispatch's archive page
- [x] Update CSS
- [x] Update register form
- [x] Update the application form

### CODE REVIEW

**Comment by olasitarska** [comment]
So I think in the application form we sign people up for the newsletter...but we never actually import this data into Campaign Monitor... yikes.

We should create a separate issue for this -- to make it use Mailchimp API. With the old emails, I can do plain old csv export, or we can ask our CSV specialist in residence @bmispelon for help ;)

**Comment by olasitarska** [comment]
Reviewed this PR -- looks great to me! 👍

**Comment by patjouk** [comment]
Oops!
I'll check [Mailchimp API ](http://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/) and see what I can do.

**Comment by patjouk** [comment]
If someone say yes to "receive the dispatch" question, they will get an email from Mailchimp asking for a confirmation and then, they will be added to the Dispatch subscriber list.
Right now, subscribed person go to a "api test" list, I'll change that before this PR get merged.
To test it, you will need to get the Mailchimp API key ([info on how to get it here](http://kb.mailchimp.com/accounts/management/about-api-keys)).
Tell me if it's working :wink:

**Comment by olasitarska** [comment]
I can confirm this is working well. @patjouk not sure if you want me to merge it now, but feel free to ping me or do it yourself anytime! :)

**Comment by olasitarska** [comment]
Also, awesome work!!

**Comment by patjouk** [comment]
I think this PR is ready:
- I've added Mailchimp API key in our WSGI files.
- I've removed Mandrill logo and replaced it by Mailchimp.
- I've updated the ID list.

So let's merge :tada: 
Thanks @olasitarska for your help!

**Comment by olasitarska** [comment]
🎉

**Pull request merged**
