### PR TITLE
WIP on fixing gulp.

### LINKED ISSUE #608: Gulp build fails when deploying website after upgrading Python image and bumping Python version to 3.7
When running `node_modules/gulp/bin/gulp.js build` after making changes to the website, the command fails and gives the following error: 

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
audited 435 packages in 2.417s
found 53 vulnerabilities (28 low, 13 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details
gulp[525]: ../src/node_contextify.cc:680:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0xa24ed0 node::Abort() [gulp]
 2: 0xa24f4e  [gulp]
 3: 0xa16e53 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xc07ac5  [gulp]
 5: 0xc080cf  [gulp]
 6: 0xc086f6 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [gulp]
 7: 0x1427159  [gulp]
./deploy.sh: line 13:   525 Aborted                 node_modules/gulp/bin/gulp.js build
```

### PR DESCRIPTION
**Pull request by carltongibson**
WIP to fix #608 — gulp is still supported and active, so we should be able to fix the tasks. 
They're not doing very much: copying some files, running a preprocessor, ... — it's got to be easier to fix gulp that swap to webpack or ... (that we're no more experts in there than we are here.) 

Update node and gulp, since it breaks on latest node. (I can't see a way to work
out which stable versions worked before.)

Begin updating gulp tasks to use gulp.series()

Run into `Task never defined: set-production` — but that seems to be present in
environment.js so I'm a bit 🤔

Pausing here, for the moment.

### CODE REVIEW

**Comment by carltongibson** [comment]
Some log extracts: 

After messing around updating for ages, clean install: 

```
$ npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

...
```

Hmmm. Do we need to address all those? 🤔

```
$ gulp --version
CLI version: 2.3.0
Local version: 4.0.2
$ gulp
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/carlton/Documents/DjangoGirls/djangogirls/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/carlton/Documents/DjangoGirls/djangogirls/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/carlton/Documents/DjangoGirls/djangogirls/gulp/tasks/build.js:4:6)

... 
 
}
```

OK, so add some `gulp.series()` declarations: 

```
(djangogirls) ~/Documents/DjangoGirls/djangogirls (fix-workflow-file)$ gulp
AssertionError [ERR_ASSERTION]: Task never defined: set-production
    at getFunction (/Users/carlton/Documents/DjangoGirls/djangogirls/node_modules/undertaker/lib/helpers/normalizeArgs.js:21:9)
    at map (/Users/carlton/Documents/DjangoGirls/djangogirls/node_modules/arr-map/index.js:20:14)
    at normalizeArgs (/Users/carlton/Documents/DjangoGirls/djangogirls/node_modules/undertaker/lib/helpers/normalizeArgs.js:30:10)
    at Gulp.series (/Users/carlton/Documents/DjangoGirls/djangogirls/node_modules/undertaker/lib/series.js:13:14)
    at Object.<anonymous> (/Users/carlton/Documents/DjangoGirls/djangogirls/gulp/tasks/build.js:4:25)
...
}
```

Grrr. OK. Let's stop.

**Comment by xavdid** [comment]
@carltongibson I spent some time on this today - looks like the `gulp@4` change was a little more of an upgrade than it lead on. The biggest change is how tasks are declared:

```js
// declaring tasks is discouraged, use exports instead:

gulp.task('sometask', ['a', 'b', 'c'], function() { ... })

// becomes

// in build.js
module.exports = gulp.series('a', 'b', 'c', async () => { ... })

// in gulpfile.js
module.exports = { sometask: require('./tasks/build') }
```

Having tasks be individual functions changes how these files are structured and the tasks are declared, but is straightforward enough. It will take more time than I expected though, so you'll have to bear with me (if you'd still like me to handle it) 😅

**Comment by carltongibson** [comment]
Hey @xavdid Thanks for the input! 

Yes I think what you say agrees with my findings thus far. I got to the point of the last error and ran out of time energy. As you see I’ve only updated a couple of the definitions so far, trying to feel my way (without finding a good How to Migrate Guide yet…)

I’d be super grateful if you do have a bit of capacity to help on this. I don’t know gulp at all so … 😬
(If you were to make a PR in this branch so we can collaborate that would be great.)

**Comment by carltongibson** [comment]
Closing in favour of #611 .

**Pull request closed without merging**
