### PR TITLE
Make menus in event-related pages capable of showing absolute path and URI

### PR DESCRIPTION
**Pull request by uranusjr**
<http://djangogirls.org/taipei/> has links to external pages in the menu (the third one from the left), and simply joining path components doesn’t work.

I use a custom template tag to detect absolute URLs (using `urllib.parse.urlparse`) and choose the right behaviour accordingly.

### CODE REVIEW

**Comment by uranusjr** [comment]
Wow yes, I didn’t read #78 and #80, but these two issues should probably be solved together. With this approach, URLs of menu items will always be either absolute, external, or relative to the event page.

With that said, I find that my change actually breaks the application list page. Shame on me for not running tests. I will fix that first.

**Comment by helenst** [comment]
Awesome - thanks for doing this. I just tried it out and it seems great! :peach:

**Comment by olasitarska** [comment]
Thaaaaaaanks! :rose:

**Comment by williln** [comment]
Thanks @uranusjr! That's awesome!

**Pull request merged**
