### PR TITLE
Changed order of EventPage, Coach and Sponsor for alphabetic by name/…

### PR DESCRIPTION
**Pull request by parodia**
…title

Hi, managing pages content became much harder after the 3rd event appeared in my admin panel. I see that now they're ordered by default chronically but maybe it would be better to order them just by title?

Same in case of sponsors and coaches - instead of default order it could be much easier to navigate if they're alphabetically :)

Justyna

### CODE REVIEW

**Comment by williln** [comment]
I am +1 on this! Thanks @parodia!

**Comment by patjouk** [comment]
Hi @parodia! Could you also add a filter to order chronically events? I need this to write the dispatch where I make a list of the latest events created :wink:

**Comment by parodia** [comment]
@patjouk as i understand right now they're sorted by default by  `pk` and you mean to sort them by `date`? Done :)

**Comment by patjouk** [comment]
By `pk` is what i need ;)

**Comment by parodia** [comment]
Ok, so now :smile:

**Comment by williln** [comment]
LGTM! @patjouk is this ready to be merged for you?

**Comment by patjouk** [comment]
@williln Let's merge it :heart: 
Thanks @parodia :sparkles:

**Comment by olasitarska** [comment]
Thanks everyone!

**Pull request merged**
