### PR TITLE
M2m coaches sponsors page event content

### PR DESCRIPTION
**Pull request by MounirMesselmeni**

### CODE REVIEW

**Comment by olasitarska** [comment]
@MounirMesselmeni Found one problem when running migrations: 

```
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, markdown_deux, django_date_extensions, suit, storages, raven_compat
  Apply all migrations: core, sessions, admin, sites, flatpages, contenttypes, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying core.0008_auto_20150605_0921... OK
  Applying core.0009_auto_20150605_0922...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/olasitarska/Envs/djangogirls.org/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/olasitarska/projects/djangogirls/core/migrations/0009_auto_20150605_0922.py", line 13, in migrate_data
    sponsor.eventpagecontent.sponsors.add(sponsor)
AttributeError: 'Sponsor' object has no attribute 'eventpagecontent'
```

**Comment by MounirMesselmeni** [comment]
@olasitarska Does this fix the problem?

**Comment by aniav** [comment]
I have just tested this and it seems to work. I want to check the changes on a semi-production database so I will be 100% sure we don't loose any data in the migration process. I hope to do that this week. Sorry nobody looked at this earlier! :+1:

**Comment by aniav** [comment]
Thanks! :tada:

**Pull request merged**
