### PR TITLE
Update pillow, and other dependencies

### PR DESCRIPTION
**Pull request by amakarudze**
Gitbot has suggested updating pillow and lxml. This PR updates dependencies in the project, including these two.

### CODE REVIEW

**Review by marksweb — APPROVED** [review]
Looks good. Checked these requirements changes myself locally.

Potential bug in the bot with removing the `trusted-host` lines but that's not a blocker.

**Comment by amakarudze** [comment]
> Looks good. Checked these requirements changes myself locally.
> 
> Potential bug in the bot with removing the `trusted-host` lines but that's not a blocker.

Thanks @marksweb. Please explain the potential bug in the bot line.

**Comment by marksweb** [comment]
@amakarudze sorry that was a misunderstanding. I thought these changes came from a bot but I think now you generated the new requirements?

I was just a bit surprised the trusted host lines had been removed.

**Comment by amakarudze** [comment]
> @amakarudze sorry that was a misunderstanding. I thought these changes came from a bot but I think now you generated the new requirements?
> 
> I was just a bit surprised the trusted host lines had been removed.

Oh I see. I didn't remove anything @marksweb. I just ran `pip-compile -U`.

**Comment by marksweb** [comment]
@amakarudze Ok, out of interest, if you run `pip freeze | grep pip-tools`, do you have version 6.2?

I feel like that set of trusted hosts was introduced in a recent version of `pip-tools`.

**Pull request merged**
