### PR TITLE
Stripe integration [#572]

### LINKED ISSUE #572: Add Stripe Integration to enable once off donations from our website
Some corporate sponsors do not have PayPal and do not want to do bank transfers, preferring to pay by credit card. Since we removed Donorbox from the website, our supporters who want to make once-off donations via credit card face challenges donating to us. We need to add Stripe integration to our website to enable once-off donations via credit card.

### PR DESCRIPTION
**Pull request by marksweb**
Second PR for stripe.

Fixes #572 

@amakarudze

### CODE REVIEW

**Review by amakarudze — APPROVED** [review]

**Comment by amakarudze** [comment]
@marksweb for some reason the website is broken again after merging this but there is nothing in the error logs to say why it's breaking. Not sure why. I really hate to revert your work again but with Sentry broken I can't figure out why it's failing. I have tested locally and it works for me. Sorry to do this to you. Thanks again for your work.

**Comment by amakarudze** [comment]
I even tried activating a the `venv` and running `python manage.py runserver` and it loads with no errors. So can't figure out why it's breaking.

**Comment by marksweb** [comment]
@amakarudze from the info on #631 it's breaking because of the data in the database.

Its technically invalid. But until recently the system hasn't cared that it was invalid.

That error you posted on that issue shows a slash in a slug value which breaks the URL path. From what I can see so far, one of my changes causes this, but it's the data that's at fault, not the code.

**Comment by amakarudze** [comment]
@marksweb I have just realized the problem. We recently upgraded the Python version from 3.5 to 3.7 but we left the old virtualenv in the same folder with the new virtualenv. So the error is `no module named stripe` because of this. I haven't reverted your work yet. Maybe it's time we delete the old virtualenv? I hadn't deleted it because the old ones were there. The web tab points to the correct virtualenv but someone it is running with the old one.

**Comment by amakarudze** [comment]
This is the traceback 

```
During handling of the above exception, another exception occurred:
**NO MATCH**
Traceback (most recent call last):
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/urls/resolvers.py", line 553, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/urls/resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/djangogirls2/djangogirls.com/djangogirls/urls.py", line 35, in <module>
    path('donate/', include('donations.urls')),
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/djangogirls2/djangogirls.com/donations/urls.py", line 3, in <module>
    from . import views
  File "/home/djangogirls2/djangogirls.com/donations/views.py", line 1, in <module>
    import stripe
ImportError: No module named 'stripe'
```

**Comment by marksweb** [comment]
@amakarudze Ok, were the requirements installed?

The package was in there prior to you reverting; https://github.com/DjangoGirls/djangogirls/pull/638/files

Screenshot 2021-08-16 at 20 23 06

**Comment by marksweb** [comment]
@amakarudze just caught your message about 2 venvs. Perhaps packages are/were installing to the wrong place and they're not available to the application because it's on the venv that isn't getting the new packages.

**Comment by amakarudze** [comment]
The data problem I manually resolved for the one that was causing the error so it's no longer in the error logs. I install the requirements in the correct virtualenv. Maybe when we reload we use the wrong env but the deployment has been working as-is @marksweb.

**Comment by marksweb** [comment]
@amakarudze Yeah, things might look like they were ok, but it feels like there's some underlying issues that have started to show themselves.

At this point, I'd just verify everything links up as you'd expect it to. Run checks like `which pip` and `which python` to verify they are in the correct venv when you're in the project directory.

Then where the build script is concerned, do similar checks to make sure everything is running as expected.

**Comment by amakarudze** [comment]
@marksweb So we have a lot of apps, 3 of which are reloaded each time we do deployment. I changed the virtualenv of one of the 3 to Python 3.7 so that was the cause. I have since changed them all and it's now loading without reverting your changes . What a relief. However, Stripe form doesn't load so maybe I have set environment variables in the wrong wsgi file and need to add to the other 2. This means I don't know now which app we are using in production. 

This is really confusing. Yeah, you are right that there are a lot of underlying issues that have started to show themselves.

Let me close the PR to revert your work. At least now we know the dot-env issue wasn't the one breaking things. 

Thanks for being available to talk this through. I honestly couldn't see anything wrong with your code so not sure why things broke. Unfortunately, I hate bringing the site down for long periods so I would always choose the revert route. So today after almost 2 hours, its back up. At least we know now why this happened.

Thanks again.

**Pull request merged**
