### PR TITLE
Added pip-tools

### PR DESCRIPTION
**Pull request by marksweb**
This adds `pip-tools` to manage requirements. Starting with `requirements.txt` pretty much as it is.

Addresses #618

### CODE REVIEW

**Comment by marksweb** [comment]
@amakarudze I'm just rebasing for the changes in main.

With that sentry update, was the main thing there the update to `sentry-sdk` and all other packages came as dependencies of that?

**Comment by amakarudze** [comment]
> @amakarudze I'm just rebasing for the changes in main.
> 
> With that sentry update, was the main thing there the update to `sentry-sdk` and all other packages came as dependencies of that?

Yes @marksweb, the main thing was to update `sentry_sdk`. I however experienced issues with `httplib2` conflicts so had to update the dependency to make the build pass. Any other changes were due to the update.

The only concern I have with keeping all packages fresh is when I tried upgrading Django version to 3.2, `django-recaptcha`,
has known issues when it comes to testing with Django 3.0 and later so I couldn't get 3 tests that have `captcha` to pass. I would upgrade packages individually for now then merge this when we are done with incremental updates.

**Comment by marksweb** [comment]
@amakarudze Perhaps I've not made it too clear how this works. It won't allow upgrades to packages which aren't compatible, and it'll show you where the compatibility issues exist.

For example, I know my project isn't ready for django 3.2 yet, so I force `requirements.in` to have `Django>3.2` and I get the following type output from `pip-compile`;

```
% pip-compile                                                    
Could not find a version that matches Django<2.3,<3.3,<4.0,>1.11,>3.2,>=1.11,>=1.8,>=2.0,>=2.2,>=2.2.14 (from -r requirements.in (line 25))
Tried: 1.1.3, 1.1.3, 1.1.4 ... it tries to get all versions of the package and tells you about here..., 3.2rc1, 3.2rc1, 3.2rc1
There are incompatible versions in the resolved dependencies:
  Django>3.2 (from -r requirements.in (line 25))
  Django>=2.2 (from django-storages[boto3]==1.11.1->-r requirements.in (line 41))
  Django>=2.2 (from administration-realbuzz[otp]==1.2.4->-r requirements.in (line 3))
  Django<2.3,>=1.8 (from django-multisite->-r requirements.in (line 27))
```

So with that I can see `django-multisite` isn't compatible. You'd likely see this from `django-recaptcha`.

I can appreciate the concerns though. When I started using this it seemed a little scary, or too good to be true. But it's been excellent at maintaining a number of projects over the last year or so because you don't have to worry about the minor versions, the dependencies of packages. You just concentrate on the packages you really need, and then set the versions of those that you want, it figures out the rest. Then you run your tests.

You can pin all of your packages and then it's just like having the classic `requirements.txt`. This is effectively what I've done here to get this started, so that we can guarantee that the generated `requirements.txt` doesn't change anything, it just enables this functionality moving forwards.

After that, what I find to be ideal is to set boundaries for requirements. For example, I've got a project which is staying on django 2.2 for now, but I want to make sure that it gets security patches when I run `pip-compile -U` (it only upgrades things in `requirements.txt` when you run this, and then you have to commit those changes of course). So my `requirements.in` looks a bit like this;

```
cryptography<3.4
easy_thumbnails
django-filer>=1.3
Django>2.2,<2.3
```

That then generates the `requirements.txt` with all the dependencies and let's you know where each package comes from;

```
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile
#
--trusted-host pypi.python.org
--trusted-host pypi.org
--trusted-host files.pythonhosted.org

cffi==1.14.6
    # via cryptography
cryptography==3.3.2
    # via -r requirements.in
django==2.2.24
    # via
    #   -r requirements.in
    #   django-filer
    #   django-mptt
    #   django-polymorphic
    #   easy-thumbnails
django-filer==2.0.2
    # via -r requirements.in
django-js-asset==1.2.2
    # via django-mptt
django-mptt==0.12.0
    # via django-filer
django-polymorphic==3.0.0
    # via django-filer
easy-thumbnails==2.7.1
    # via
    #   -r requirements.in
    #   django-filer
pillow==8.3.1
    # via easy-thumbnails
pycparser==2.20
    # via cffi
pytz==2021.1
    # via django
six==1.16.0
    # via cryptography
sqlparse==0.4.1
    # via django
unidecode==1.1.2
    # via django-filer
```

**Comment by amakarudze** [comment]
Thanks @marksweb for the explanation. I am currently the only one doing deployment and therefore the only one doing reverts when something fails in production hence my hesitation. If it doesn't force updates for packages with conflicts then we are good.

**Comment by marksweb** [comment]
@amakarudze I can appreciate you not wanting things to go wrong there then! I'm in a similar situation at work where I'm part of a 2 person ops team where the other person has found a new job 😬 
I also don't want things to go wrong when I'm deploying changes!!

We use AWS, so I don't have too much experience with python anywhere besides setting up an account personally a while back. But maybe there's some ways we can build a more resilient build pipeline to gain a bit of reassurance.

**Comment by carltongibson** [comment]
Hey both. Give me a chance to look at this.

@marksweb Once the other changes are in can you rebase to make the diff smaller? Thanks. 👍

**Comment by marksweb** [comment]
@carltongibson Just noticed the changes. Most of them are from another PR which has been merged;

https://github.com/DjangoGirls/djangogirls/commit/a30bb63053094e06f6a1a4bdc337d2f96673362e

Might just close this & setup another branch off main as the change here is tiny.

**Comment by carltongibson** [comment]
(Or force push... — as you wish)

**Pull request closed without merging**
