### PR TITLE
Fixed lookups when outputting application answers

### PR DESCRIPTION
**Pull request by robcharlwood**
Fix broken lookups in email template for application responses. :)

#25

### CODE REVIEW

**Comment by olasitarska** [comment]
Hah, touch doesn't really work on Github, but I know where you come from :joy:

**Comment by robcharlwood** [comment]
haha! Bah! Old habits die hard @olasitarska :-D

**Comment by robcharlwood** [comment]
@olasitarska renamed ;)

**Comment by olasitarska** [comment]
I think on Github you can just use #numberofissue or refs #numberofissue

**Comment by olasitarska** [comment]
Thanks! you :rocket:!

**Pull request merged**
