### PR TITLE
Check codecov integration with GitHub Actions

### PR DESCRIPTION
**Pull request by amakarudze**
Testing if codecov section works with GitHub Actions as part of GitHub Actions clean up.

### CODE REVIEW

**Comment by amakarudze** [comment]
@marksweb do you think you can help us integrate Codecov and GitHub Actions?

**Comment by marksweb** [comment]
@amakarudze Yeah there's essentially a pre-built action for running coverage.

Is it codecov that you'd like?

https://github.com/marketplace/actions/codecov

**Comment by amakarudze** [comment]
> @amakarudze Yeah there's essentially a pre-built action for running coverage.
> 
> Is it codecov that you'd like?
> 
> https://github.com/marketplace/actions/codecov

@marksweb We were using codecov before but we are no hard set on it I think. We just moved from Travis to Actions so I think we can use the built-in one. Thanks

**Comment by amakarudze** [comment]
The issue was resolved by #642.

**Pull request closed without merging**
