### PR TITLE
Porting to python3

### PR DESCRIPTION
**Pull request by MounirMesselmeni**
Also removing unused imports, fixing some PEP8 errors, using __future__ and django python_2_unicode_compatible to enable backwards to Python 2 if desired

### CODE REVIEW

**Comment by aniav** [comment]
Seeems ok! Can someone test it locally and confirm everything is ok? If not I will do it later today :)

**Comment by olasitarska** [comment]
On it! :rocket:

**Comment by olasitarska** [comment]
On Python 2, everything seems to work. On Python 3, I got this error while trying to do `./manage.py new_event`:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/olasitarska/projects/djangogirls/core/management/commands/new_event.py", line 211, in handle
    self.add_default_content(page)
  File "/Users/olasitarska/projects/djangogirls/core/management/commands/new_event.py", line 128, in add_default_content
    content='<div style="text-align: center;"><h1>Free programming workshop for women</h1><h2>Build your first website at EuroPython 2014 in Berlin!</h2><a class="btn" href="#value">Learn more »</a></div>')
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 878, in as_sql
    for obj in self.query.objs
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 878, in <listcomp>
    for obj in self.query.objs
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 876, in <listcomp>
    for f in fields
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/fields/files.py", line 301, in pre_save
    file.save(file.name, file, save=False)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/db/models/fields/files.py", line 89, in save
    self.name = self.storage.save(name, content)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/core/files/storage.py", line 51, in save
    name = self._save(name, content)
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/core/files/storage.py", line 223, in _save
    for chunk in content.chunks():
  File "/Users/olasitarska/Envs/djangogirls3/lib/python3.4/site-packages/django/core/files/base.py", line 78, in chunks
    data = self.read(chunk_size)
  File "/Users/olasitarska/Envs/djangogirls3/bin/../lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by olasitarska** [comment]
@MounirMesselmeni, could you take a look?

**Comment by olasitarska** [comment]
```
👉 heroku logs --app djangogirls
2015-06-04T15:15:17.404568+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
2015-06-04T15:15:17.404570+00:00 app[web.1]:     return self.nodelist.render(context)
2015-06-04T15:15:17.404574+00:00 app[web.1]:     bit = self.render_node(node, context)
2015-06-04T15:15:17.404572+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 844, in render
2015-06-04T15:15:17.404575+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
2015-06-04T15:15:17.404577+00:00 app[web.1]:     return node.render(context)
2015-06-04T15:15:17.404578+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/templatetags/static.py", line 106, in render
2015-06-04T15:15:17.404580+00:00 app[web.1]:     url = self.url(context)
2015-06-04T15:15:17.404583+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 16, in url
2015-06-04T15:15:17.404593+00:00 app[web.1]:     return static(path)
2015-06-04T15:15:17.404594+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 9, in static
2015-06-04T15:15:17.404596+00:00 app[web.1]:     return staticfiles_storage.url(path)
2015-06-04T15:15:17.404598+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/functional.py", line 224, in inner
2015-06-04T15:15:17.404600+00:00 app[web.1]:     self._setup()
2015-06-04T15:15:17.404601+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 391, in _setup
2015-06-04T15:15:17.404603+00:00 app[web.1]:     self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
2015-06-04T15:15:17.404605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/files/storage.py", line 303, in get_storage_class
2015-06-04T15:15:17.404607+00:00 app[web.1]:     return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
2015-06-04T15:15:17.404609+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/module_loading.py", line 26, in import_string
2015-06-04T15:15:17.404610+00:00 app[web.1]:     module = import_module(module_path)
2015-06-04T15:15:17.404612+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/importlib/__init__.py", line 109, in import_module
2015-06-04T15:15:17.404614+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2015-06-04T15:15:17.404616+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
2015-06-04T15:15:17.404618+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
2015-06-04T15:15:17.404619+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
2015-06-04T15:15:17.404621+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
2015-06-04T15:15:17.404628+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/storages/backends/s3boto.py", line 9, in <module>
2015-06-04T15:15:17.404625+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
2015-06-04T15:15:17.404627+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
2015-06-04T15:15:17.404623+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1129, in _exec
2015-06-04T15:15:17.404667+00:00 app[web.1]:     from StringIO import StringIO  # noqa
2015-06-04T15:15:17.404671+00:00 app[web.1]:
2015-06-04T15:15:17.404670+00:00 app[web.1]: ImportError: No module named 'StringIO'
2015-06-04T15:15:17.404675+00:00 app[web.1]:
2015-06-04T15:15:17.404673+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2015-06-04T15:15:17.404676+00:00 app[web.1]: Traceback (most recent call last):
2015-06-04T15:15:17.404678+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/storages/backends/s3boto.py", line 7, in <module>
2015-06-04T15:15:17.404679+00:00 app[web.1]:     from cStringIO import StringIO
2015-06-04T15:15:17.404681+00:00 app[web.1]: ImportError: No module named 'cStringIO'
2015-06-04T15:15:17.404682+00:00 app[web.1]:
2015-06-04T15:15:17.404686+00:00 app[web.1]:
2015-06-04T15:15:17.404684+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2015-06-04T15:15:17.404687+00:00 app[web.1]: Traceback (most recent call last):
2015-06-04T15:15:17.404691+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2015-06-04T15:15:17.404689+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 93, in handle
2015-06-04T15:15:17.404692+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
2015-06-04T15:15:17.404694+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2015-06-04T15:15:17.404696+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/whitenoise/base.py", line 62, in __call__
2015-06-04T15:15:17.404697+00:00 app[web.1]:     return self.application(environ, start_response)
2015-06-04T15:15:17.404701+00:00 app[web.1]:     response = self.get_response(request)
2015-06-04T15:15:17.404704+00:00 app[web.1]:     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
2015-06-04T15:15:17.404699+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
2015-06-04T15:15:17.404707+00:00 app[web.1]:     return callback(request, **param_dict)
2015-06-04T15:15:17.404703+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 153, in get_response
2015-06-04T15:15:17.404706+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 243, in handle_uncaught_exception
2015-06-04T15:15:17.404709+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
2015-06-04T15:15:17.404711+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2015-06-04T15:15:17.404712+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/views/defaults.py", line 47, in server_error
2015-06-04T15:15:17.404714+00:00 app[web.1]:     return http.HttpResponseServerError(template.render(Context({})))
2015-06-04T15:15:17.404716+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 148, in render
2015-06-04T15:15:17.404717+00:00 app[web.1]:     return self._render(context)
2015-06-04T15:15:17.404720+00:00 app[web.1]:     return self.nodelist.render(context)
2015-06-04T15:15:17.404719+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
2015-06-04T15:15:17.404722+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 844, in render
2015-06-04T15:15:17.404727+00:00 app[web.1]:     return node.render(context)
2015-06-04T15:15:17.404724+00:00 app[web.1]:     bit = self.render_node(node, context)
2015-06-04T15:15:17.404725+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
2015-06-04T15:15:17.404729+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 126, in render
2015-06-04T15:15:17.404737+00:00 app[web.1]:     return compiled_parent._render(context)
2015-06-04T15:15:17.404739+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
2015-06-04T15:15:17.404740+00:00 app[web.1]:     return self.nodelist.render(context)
2015-06-04T15:15:17.404742+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 844, in render
2015-06-04T15:15:17.404743+00:00 app[web.1]:     bit = self.render_node(node, context)
2015-06-04T15:15:17.404745+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
2015-06-04T15:15:17.404747+00:00 app[web.1]:     return node.render(context)
2015-06-04T15:15:17.404748+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 1136, in render
2015-06-04T15:15:17.404750+00:00 app[web.1]:     return func(*resolved_args, **resolved_kwargs)
2015-06-04T15:15:17.404752+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_static.py", line 17, in static
2015-06-04T15:15:17.404757+00:00 app[web.1]:     return staticfiles_storage.url(path)
2015-06-04T15:15:17.404755+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 9, in static
2015-06-04T15:15:17.404753+00:00 app[web.1]:     return _static(path)
2015-06-04T15:15:17.404759+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/functional.py", line 224, in inner
2015-06-04T15:15:17.404760+00:00 app[web.1]:     self._setup()
2015-06-04T15:15:17.404762+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 391, in _setup
2015-06-04T15:15:17.404764+00:00 app[web.1]:     self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
2015-06-04T15:15:17.404766+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/files/storage.py", line 303, in get_storage_class
2015-06-04T15:15:17.404767+00:00 app[web.1]:     return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
2015-06-04T15:15:17.404769+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/module_loading.py", line 26, in import_string
2015-06-04T15:15:17.404771+00:00 app[web.1]:     module = import_module(module_path)
2015-06-04T15:15:17.404773+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/importlib/__init__.py", line 109, in import_module
2015-06-04T15:15:17.404774+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2015-06-04T15:15:17.404776+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
2015-06-04T15:15:17.404778+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
2015-06-04T15:15:17.404779+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
2015-06-04T15:15:17.404781+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
2015-06-04T15:15:17.404786+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
2015-06-04T15:15:17.404788+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/storages/backends/s3boto.py", line 9, in <module>
2015-06-04T15:15:17.404783+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1129, in _exec
2015-06-04T15:15:17.404789+00:00 app[web.1]:     from StringIO import StringIO  # noqa
2015-06-04T15:15:17.404785+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
2015-06-04T15:15:17.404791+00:00 app[web.1]: ImportError: No module named 'StringIO'
```

**Pull request merged**
