### PR TITLE
Coach form

### PR DESCRIPTION
**Pull request by peconia**
I added coach applications and messaging, similar to the applications for attendees but without the scoring. This could possibly fix issue #156. I added some unit tests and amended existing ones slightly so all the tests are passing. Everything works for me locally but I am not sure if this is good enough, please let me know what should be fixed and I'll do my best. Thanks! :scream: :tangerine: :hamster:

### CODE REVIEW

**Comment by olasitarska** [comment]
Hi @peconia!

Thank you for working on this -- I see that this took a lot of effort!

I think it'd be much better if we just modify and refactor existing applications app to allow for multiple forms - this way organizers can create forms about whatever they want, and are not limited to just two forms. 

I might be wrong though, so happy to hear a second opinion from any @DjangoGirls/committers or @DjangoGirls/support?

**Comment by helenst** [comment]
@olasitarska @peconia I agree that this is awesome work and it would be really great to be able to manage coaches more nicely! There is a lot of duplicated code between this and the applications module so it would be good to wrap it all up into a single codebase - having the ability to extend to more forms might be nice too :) :whale::sunflower:

**Comment by peconia** [comment]
Oops, I kind of forgot this. If I ever find the time I'll have another go, but if anyone else wishes to fix it in the meantime then please don't wait for me. Thanks for the feedback :rabbit: :heart:

**Comment by pguatura** [comment]
Hi! I've been looking for this feature and I'm very glad to see that someone already though about this and started developing it. I was thinking about continuing the development considering the feedback, but I haven't contributed to anything else on this repository. Do you mind if I try or do you think it's better if i start with something else?

**Pull request closed without merging**
