### PR TITLE
Empty chartxtfields

### PR DESCRIPTION
**Pull request by khdc-me**
Django Docs at (https://docs.djangoproject.com/en/2.1/ref/models/fields/)

Removed all "null=False" and "blank=False" from all field types (not foreign keys, etc).

For "all field types," default value for null is False and default value for blank is False. No need to set/assign.

### CODE REVIEW

**Comment by khdc-me** [comment]
Closes #83

**Comment by khdc-me** [comment]
According to [codecov's site](https://docs.codecov.io/docs/error-reference#section-missing-base-commit):
"In order to produce an accurate coverage comparison, Codecov must have the coverage report for the pull request base.

Best Practice: Always fork a branch from a successful CI commit that has coverage uploaded, as illustrated below.

This issue occurs when the base commit (the parent commit of the first commit on the pull request) did not upload coverage and/or failed CI tests."

I forked 'master', pulled before submitting branch b/c new merge since I forked, rebased my branch onto master (no conflicts), pushed onto my git, initiated this PR.

If any of this is incorrect, and is causing the coverage issue, please let me know.

**Comment by khdc-me** [comment]
Would be awesome to see it merged.

**Comment by aniav** [comment]
👍

**Pull request merged**
